import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'pt' | 'es' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

export const translations = {
    pt: {
        // General
        'app.title': 'Amazon Sem Segredos',
        'search.placeholder': 'Digite palavra-chave ou ASIN',
        'search.button': 'Pesquisar',
        'searching': 'Pesquisando...',
        'suppliers.link': 'Encontrar Fornecedores no Alibaba',
        'rows.selected': 'Linhas Selecionadas',
        'filter.results': 'Filtrar Resultados',

        // Product Finder Headers
        'col.product_details': 'Detalhes do Produto',
        'col.asin': 'ASIN',
        'col.brand': 'Marca',
        'col.price': 'Preço',
        'col.sales': 'Vendas',
        'col.sales_graph': 'Gráfico de Vendas',
        'col.ranking_bsr': 'Ranking (BSR)',
        'col.revenue': 'Receita',
        'col.bsr': 'BSR',
        'col.fba_fees': 'Taxas FBA',
        'col.active_sellers': 'Vendedores Ativos',

        // Summary Cards
        'summary.search_volume': 'Volume de Busca',
        'summary.total_revenue': 'Receita Total',
        'summary.avg_revenue': 'Receita Média',
        'summary.avg_price': 'Preço Médio',
        'summary.avg_bsr': 'BSR Médio',
        'summary.avg_reviews': 'Avaliações Médias',
        'summary.success_score': 'Pontuação de Sucesso',

        // Empty States / Errors
        'error.no_products': 'Nenhum produto encontrado. Inicie uma pesquisa.',

        // Product Categories
        'category.Beauty': 'Beleza',
        'category.Electronics': 'Eletrônicos',
        'category.Home': 'Casa',
        'category.Kitchen': 'Cozinha',
        'category.Toys': 'Brinquedos',
        'category.Sports': 'Esportes',
        'category.Unknown': 'Geral',

        // Modules
        'module.dashboard': 'Visão Geral',
        'module.mentor': 'Mentor Virtual',
        'module.product_finder': 'Buscador de Produtos',
        'module.profit_calculator': 'Calculadora de Lucro Real',
        'module.listing_optimizer': 'Criador de Listing',
        'module.ads_manager': 'Gerenciador de Ads',
        'module.settings': 'Configurações',
        'module.logout': 'Sair',
        'auth.forgot_password': 'Esqueci minha senha',
        'auth.reset_password': 'Redefinir Senha',
        'auth.back_to_login': 'Voltar para Login',
        'auth.send_reset_link': 'Enviar Link de Recuperação',
        'auth.reset_email_sent': 'Link de recuperação enviado! Verifique seu e-mail.',

        // Profile & Billing
        'profile.title': 'Perfil',
        'profile.change_password': 'Trocar Senha',
        'profile.buy_credits': 'Comprar Créditos',
        'profile.change_plan': 'Trocar de Plano',
        'profile.current_plan': 'Plano Atual',
        'profile.admin_label': 'Administrador',
        'profile.pro_label': 'Plano Pro',
        'profile.welcome': 'Bem-vindo',

        // Plans
        'plans.starter': 'Starter',
        'plans.starter_desc': 'Ideal para começar',
        'plans.starter_features': '5 Créditos Iniciais',
        'plans.pro': 'Plano Pro',
        'plans.pro_desc': 'Para vendedores em crescimento',
        'plans.pro_price': '29€/mês',
        'plans.premium': 'Plano Premium',
        'plans.premium_desc': 'Poder total da IA',
        'plans.premium_price': '49€/mês',
        'plans.select': 'Escolher Plano',
        'plans.free': 'Grátis',

        // Modal
        'modal.est_sales': 'Vendas Est.',
        'modal.est_revenue': 'Receita Est.',
        'modal.price': 'Preço',
        'modal.sellers': 'Vendedores',
        'modal.reviews': 'Avaliações',
        'modal.score': 'Score',
        'modal.fba_fees': 'Taxas FBA',
        'modal.view_amazon': 'Ver na Amazon',
        'modal.units_month': 'Unid. / Mês',
        'modal.footer_disclaimer': 'Dados fornecidos pela Amazon SP-API • Estimativas baseadas na categoria',
        'modal.unknown_brand': 'Marca Desconhecida',
        'mentor.title': 'Conheça nossos 9 Agentes Especializados',
        'mentor.subtitle': 'Cada um é preparado para lidar com desafios específicos.',

        // Listing Optimizer
        'lo.intro': 'Olá! Sou seu especialista em Amazon. Vamos criar um anúncio vencedor para a Amazon Espanha? Primeiro, qual é o nome do seu produto?',
        'lo.q.productName': 'Qual é o nome do seu produto?',
        'lo.q.category': 'Qual a categoria dele? (Ex: Cozinha, Esportes, Eletrônicos)',
        'lo.q.material': 'De qual material ele é feito? (Ex: Aço Inox, Algodão Orgânico)',
        'lo.q.benefits': 'Quais são os principais benefícios? (Liste 2 ou 3)',
        'lo.q.differentiators': 'O que o diferencia dos concorrentes? (Seu "Tchan")',
        'lo.q.audience': 'Quem é o seu público-alvo? (Ex: Mães, Atletas, Gamers)',
        'lo.q.problem': 'Que problema ele resolve para o cliente?',
        'lo.q.usage': 'Qual o uso principal? (Ex: Dia a dia, Presente, Viagem)',
        'lo.processing.text': 'Perfeito! Estou criando seu anúncio otimizado agora. Isso pode levar alguns segundos...',
        'lo.success.text': 'Anúncio de texto gerado com sucesso! Agora, para finalizar, preciso que você envie uma foto do produto (fundo branco é ideal) para que eu possa gerar variações visuais.',
        'lo.error.text': 'Ops, tive um problema ao gerar o texto. Tente novamente.',
        'lo.processing.image': 'Recebi a imagem! Estou gerando 3 variações otimizadas para o anúncio...',
        'lo.success.image': 'Pronto! Seu anúncio está completo. Veja abaixo.',
        'lo.error.image': 'Erro ao gerar imagens. Mas confira o texto abaixo.',
        'lo.ui.assistant': 'Assistente',
        'lo.ui.history': 'Histórico',
        'lo.ui.history.empty': 'Nenhum listing salvo.',
        'lo.ui.upload': 'Clique para enviar foto',
        'lo.ui.input_placeholder': 'Digite sua resposta...',
        'lo.ui.title': 'Seu anúncio aparecerá aqui',
        'lo.ui.subtitle': 'Responda as perguntas ao lado para que nossa IA crie um anúncio de alta conversão para seu produto.',
        'lo.ui.save': 'Salvar Listing',
        'lo.ui.generating_images': 'Gerando Imagens...',
        'analyze.button': 'Analisar Concorrência',
        'analyze.modal_title': 'Análise de Concorrência IA',
        'analyze.weaknesses': 'Fraquezas da Concorrência',
        'analyze.improvements': 'Oportunidades de Melhoria',
        'analyze.processing': 'Extraindo reviews e analisando com IA...',
        'analyze.error': 'Erro ao analisar concorrência.',
        'analyze.credits_info': 'Consome 5 créditos premium',
        'analyze.recent_reviews': 'Últimos Reviews',
        'summary.feb_2026': 'Fev 2026',
        'lock.title': 'Limite de Créditos Atingido',

        // Profit Simulator
        'sim.title': 'Simulador de Lucro Real',
        'sim.product_cost': 'Custo do Produto',
        'sim.product_cost_help': 'O preço que você paga ao seu fornecedor por unidade, incluindo o frete até o seu armazém.',
        'sim.tax_rate': 'Imposto (%)',
        'sim.tax_rate_help': 'A alíquota de imposto do seu negócio (ex: SIMPLES Nacional). Geralmente entre 4% e 15% no Brasil.',
        'sim.op_expenses': 'Despesas Operacionais',
        'sim.op_expenses_help': 'Custo de embalagem, etiquetas e serviço de preparação por unidade.',
        'sim.ads_ppc': 'Investimento em Ads (PPC)',
        'sim.ads_ppc_help': 'Quanto você planeja gastar em Amazon Advertising para obter uma venda. Um começo seguro é entre 10-15% do preço.',
        'sim.total_expenses': 'Total de Despesas',
        'sim.net_profit': 'Lucro Líquido',
        'sim.net_margin': 'Margem Líquida',
        'sim.roi': 'ROI (Retorno)',
        'sim.export_pdf': 'Exportar Relatório PDF',
        'sim.fba_vs_fbm': 'Comparação FBA vs FBM',
        'sim.amazon_fulfilment': 'Logística da Amazon (FBA)',
        'sim.your_fulfilment': 'Sua Logística (FBM)',
        'sim.item_price': 'Preço do Item',
        'sim.delivery_charge': 'Taxa de Entrega',
        'sim.amazon_fees': 'Taxas da Amazon',
        'sim.referral_fee': 'Taxa de Indicação',
        'sim.fulfilment_cost': 'Custo de Logística',
        'sim.storage_cost': 'Custo de Armazenamento',
        'sim.jan_sep': 'Janeiro-Setembro',
        'sim.oct_dec': 'Outubro-Dezembro',
        'sim.storage_per_unit': 'Custo mensal de armazenamento por unidade',
        'sim.avg_inventory': 'Unidades de inventário médias armazenadas',
        'sim.est_sales_month': 'Unidades mensais estimadas vendidas',
        'sim.storage_per_sold': 'Custo de armazenamento por unidade vendida',
        'sim.fixed_closing': 'Fixed Closing Fee',
        'sim.variable_closing': 'Variable Closing Fee',
        'sim.digital_services': 'Taxa de serviços digitais',
        'sim.misc_cost': 'Custo Diverso',
        'sim.shipping_out': 'Portes de Envio',
        'sim.total_sales_price': 'Preço de Venda Final',
        'sim.other_costs': 'Outros Custos',
        'sim.vat': 'IVA / Impostos',
        'sim.cogs': 'Custo da Mercadoria (COGS)',
        'sim.net_proceeds': 'Receita Líquida',
        'sim.search_placeholder': 'Buscar ASIN ou Palavra-chave...',
        'sim.search_button': 'Buscar Produto',
        'sim.search_another': 'Buscar outro produto',
    },
    es: {
        // General
        'app.title': 'Amazon Sin Secretos',
        'search.placeholder': 'Ingrese palabra clave o ASIN',
        'search.button': 'Buscar',
        'searching': 'Buscando...',
        'suppliers.link': 'Encontrar Proveedores en Alibaba',
        'rows.selected': 'Filas Seleccionadas',
        'filter.results': 'Filtrar Resultados',

        // Product Finder Headers
        'col.product_details': 'Detalles del Producto',
        'col.asin': 'ASIN',
        'col.brand': 'Marca',
        'col.price': 'Precio',
        'col.sales': 'Ventas',
        'col.sales_graph': 'Gráfico de Ventas',
        'col.ranking_bsr': 'Clasificación (BSR)',
        'col.revenue': 'Ingresos',
        'col.bsr': 'BSR',
        'col.fba_fees': 'Tarifas FBA',
        'col.active_sellers': 'Vendedores Activos',

        // Summary Cards
        'summary.search_volume': 'Volumen de Búsqueda',
        'summary.total_revenue': 'Ingresos Totales',
        'summary.avg_revenue': 'Ingresos Promedio',
        'summary.avg_price': 'Precio Promedio',
        'summary.avg_bsr': 'BSR Promedio',
        'summary.avg_reviews': 'Reseñas Promedio',
        'summary.success_score': 'Puntuación de Éxito',

        // Empty States / Errors
        'error.no_products': 'No se encontraron productos. Inicie una búsqueda.',

        // Product Categories
        'category.Beauty': 'Belleza',
        'category.Electronics': 'Electrónica',
        'category.Home': 'Hogar',
        'category.Kitchen': 'Cocina',
        'category.Toys': 'Juguetes',
        'category.Sports': 'Deportes',
        'category.Unknown': 'General',

        // Modules
        'module.dashboard': 'Visión General',
        'module.mentor': 'Mentor Virtual',
        'module.product_finder': 'Buscador de Productos',
        'module.profit_calculator': 'Calculadora de Beneficio Real',
        'module.listing_optimizer': 'Optimizador de Listados',
        'module.ads_manager': 'Gestor de Anuncios',
        'module.settings': 'Configuración',
        'module.logout': 'Cerrar Sesión',

        // Modal
        'modal.est_sales': 'Ventas Est.',
        'modal.est_revenue': 'Ingresos Est.',
        'modal.price': 'Precio',
        'modal.sellers': 'Vendedores',
        'modal.reviews': 'Reseñas',
        'modal.score': 'Puntuación',
        'modal.fba_fees': 'Tarifas FBA',
        'modal.view_amazon': 'Ver en Amazon',
        'modal.units_month': 'Unid. / Mes',
        'modal.footer_disclaimer': 'Datos proporcionados por Amazon SP-API • Estimaciones basadas en la categoría',
        'modal.unknown_brand': 'Marca Desconocida',
        'mentor.title': 'Conozca nuestros 9 Agentes Especializados',
        'mentor.subtitle': 'Cada uno está preparado para enfrentar desafíos específicos.',

        // Listing Optimizer
        'lo.intro': '¡Hola! Soy tu experto en Amazon. ¿Vamos a crear un anuncio ganador para Amazon España? Primero, ¿cuál es el nombre de tu producto?',
        'lo.q.productName': '¿Cuál es el nombre de tu producto?',
        'lo.q.category': '¿Cuál es su categoría? (Ej: Cocina, Deportes, Electrónica)',
        'lo.q.material': '¿De qué material está hecho? (Ej: Acero Inoxidable, Algodón Orgánico)',
        'lo.q.benefits': '¿Cuáles son los principales beneficios? (Lista 2 o 3)',
        'lo.q.differentiators': '¿Qué lo diferencia de la competencia?',
        'lo.q.audience': '¿Quién es tu público objetivo? (Ej: Madres, Atletas, Gamers)',
        'lo.q.problem': '¿Qué problema resuelve para el cliente?',
        'lo.q.usage': '¿Cuál es el uso principal? (Ej: Diario, Regalo, Viaje)',
        'lo.processing.text': '¡Perfecto! Estoy creando tu anuncio optimizado ahora. Esto puede tardar unos segundos...',
        'lo.success.text': '¡Anuncio de texto generado con éxito! Ahora, para finalizar, necesito que envíes una foto del producto (fondo blanco es ideal) para generar variaciones visuales.',
        'lo.error.text': 'Ups, tuve un problema al generar el texto. Inténtalo de nuevo.',
        'lo.processing.image': '¡Recibí la imagen! Estoy generando 3 variaciones optimizadas...',
        'lo.success.image': '¡Listo! Tu anuncio está completo. Mira abajo.',
        'lo.error.image': 'Error al generar imágenes. Pero revisa el texto abajo.',
        'lo.ui.assistant': 'Asistente',
        'lo.ui.history': 'Historial',
        'lo.ui.history.empty': 'Ningún listado guardado.',
        'lo.ui.upload': 'Clic para enviar foto',
        'lo.ui.input_placeholder': 'Escribe tu respuesta...',
        'lo.ui.title': 'Tu anuncio aparecerá aquí',
        'lo.ui.subtitle': 'Responde las preguntas para que nuestra IA cree un anuncio de alta conversión.',
        'lo.ui.save': 'Guardar Listado',
        'lo.ui.generating_images': 'Generando Imágenes...',
        'analyze.button': 'Analizar Competencia',
        'analyze.modal_title': 'Análisis de Competencia IA',
        'analyze.weaknesses': 'Debilidades de la Competencia',
        'analyze.improvements': 'Oportunidades de Mejora',
        'analyze.processing': 'Extrayendo reseñas y analizando con IA...',
        'analyze.error': 'Error al analizar la competencia.',
        'analyze.credits_info': 'Consume 5 créditos premium',
        'analyze.recent_reviews': 'Últimas Reseñas',
        'summary.feb_2026': 'Feb 2026',

        // Profit Simulator
        'sim.title': 'Simulador de Lucro Real',
        'sim.product_cost': 'Costo del Producto',
        'sim.product_cost_help': 'El precio que paga a su proveedor por unidad, incluido el envío a su almacén.',
        'sim.tax_rate': 'Impuesto (%)',
        'sim.tax_rate_help': 'La tasa de impuestos de su negocio. Generalmente entre 4% y 15% en Brasil.',
        'sim.op_expenses': 'Gastos Operativos',
        'sim.op_expenses_help': 'Costo de embalaje, etiquetas y servicio de preparación por unidad.',
        'sim.ads_ppc': 'Inversión en Ads (PPC)',
        'sim.ads_ppc_help': 'Cuánto planea gastar en Amazon Advertising para obtener una venta. Un comienzo seguro es entre 10-15% del precio.',
        'sim.total_expenses': 'Gastos Totales',
        'sim.net_profit': 'Beneficio Neto',
        'sim.net_margin': 'Margen Neto',
        'sim.roi': 'ROI (Retorno)',
        'sim.export_pdf': 'Exportar Informe PDF',
        'sim.fba_vs_fbm': 'Comparativa FBA vs FBM',
        'sim.amazon_fulfilment': 'Logística de Amazon (FBA)',
        'sim.your_fulfilment': 'Tu Logística (FBM)',
        'sim.item_price': 'Precio del Artículo',
        'sim.delivery_charge': 'Gasto de Envío',
        'sim.amazon_fees': 'Tarifas de Amazon',
        'sim.referral_fee': 'Tarifa de Referencia',
        'sim.fulfilment_cost': 'Coste de Logística',
        'sim.storage_cost': 'Coste de Almacenamiento',
        'sim.jan_sep': 'Enero-Septiembre',
        'sim.oct_dec': 'Octubre-Diciembre',
        'sim.storage_per_unit': 'Coste mensual de almacenamiento por unidad',
        'sim.avg_inventory': 'Unidades de inventario media almacenadas',
        'sim.est_sales_month': 'Unidades mensuales estimadas vendidas',
        'sim.storage_per_sold': 'Coste de almacenamiento por unidad vendida',
        'sim.fixed_closing': 'Fixed Closing Fee',
        'sim.variable_closing': 'Variable Closing Fee',
        'sim.digital_services': 'Tasa de servicios digitales',
        'sim.misc_cost': 'Costes Diversos',
        'sim.shipping_out': 'Gasto de Envío',
        'sim.total_sales_price': 'Precio de Venta Final',
        'sim.other_costs': 'Otros Costes',
        'sim.vat': 'IVA / Impuestos',
        'sim.cogs': 'Coste del Producto (COGS)',
        'sim.net_proceeds': 'Ingresos Netos',
        'sim.search_placeholder': 'Buscar ASIN o Palabra clave...',
        'sim.search_button': 'Buscar Producto',
        'sim.search_another': 'Buscar otro producto',

        // Plans
        'plans.starter': 'Starter',
        'plans.starter_desc': 'Ideal para comenzar',
        'plans.starter_features': '5 Créditos Iniciales',
        'plans.pro': 'Plan Pro',
        'plans.pro_desc': 'Para vendedores en crecimiento',
        'plans.pro_price': '29€/mes',
        'plans.premium': 'Plano Premium',
        'plans.premium_desc': 'Poder total de la IA',
        'plans.premium_price': '49€/mes',
        'plans.select': 'Seleccionar Plan',
        'plans.free': 'Grátis',
    },
    en: {
        // General
        'app.title': 'Amazon Secrets Revealed',
        'search.placeholder': 'Enter keyword or ASIN',
        'search.button': 'Search',
        'searching': 'Searching...',
        'suppliers.link': 'Find Suppliers on Alibaba',
        'rows.selected': 'Rows Selected',
        'filter.results': 'Filter Results',

        // Product Finder Headers
        'col.product_details': 'Product Details',
        'col.asin': 'ASIN',
        'col.brand': 'Brand',
        'col.price': 'Price',
        'col.sales': 'Sales',
        'col.sales_graph': 'Sales Graph',
        'col.ranking_bsr': 'Ranking (BSR)',
        'col.revenue': 'Revenue',
        'col.bsr': 'BSR',
        'col.fba_fees': 'FBA Fees',
        'col.active_sellers': 'Active Sellers',

        // Summary Cards
        'summary.search_volume': 'Search Volume',
        'summary.total_revenue': 'Total Revenue',
        'summary.avg_revenue': 'Avg Revenue',
        'summary.avg_price': 'Avg Price',
        'summary.avg_bsr': 'Avg BSR',
        'summary.avg_reviews': 'Avg Reviews',
        'summary.success_score': 'Success Score',

        // Empty States / Errors
        'error.no_products': 'No products found. Start a search.',

        // Product Categories
        'category.Beauty': 'Beauty',
        'category.Electronics': 'Electronics',
        'category.Home': 'Home',
        'category.Kitchen': 'Kitchen',
        'category.Toys': 'Toys',
        'category.Sports': 'Sports',
        'category.Unknown': 'General',

        // Modules
        'module.dashboard': 'Overview',
        'module.mentor': 'Virtual Mentor',
        'module.product_finder': 'Product Finder',
        'module.profit_calculator': 'Real Profit Calculator',
        'module.listing_optimizer': 'Listing Optimizer',
        'module.ads_manager': 'Ads Manager',
        'module.settings': 'Settings',
        'module.logout': 'Logout',

        // Modal
        'modal.est_sales': 'Est. Sales',
        'modal.est_revenue': 'Est. Revenue',
        'modal.price': 'Price',
        'modal.sellers': 'Sellers',
        'modal.reviews': 'Reviews',
        'modal.score': 'Score',
        'modal.fba_fees': 'FBA Fees',
        'modal.view_amazon': 'View on Amazon',
        'modal.units_month': 'Units / Month',
        'modal.footer_disclaimer': 'Data provided by Amazon SP-API • Estimates based on category',
        'modal.unknown_brand': 'Unknown Brand',
        'mentor.title': 'Our 9 Specialized Agents',
        'mentor.subtitle': 'Each agent is trained to solve specific business challenges.',

        // Listing Optimizer
        'lo.intro': 'Hello! I am your Amazon expert. Let\'s create a winning listing for Amazon Spain? First, what is the name of your product?',
        'lo.q.productName': 'What is the name of your product?',
        'lo.q.category': 'What is its category? (Ex: Kitchen, Sports, Electronics)',
        'lo.q.material': 'What material is it made of? (Ex: Stainless Steel, Organic Cotton)',
        'lo.q.benefits': 'What are the main benefits? (List 2 or 3)',
        'lo.q.differentiators': 'What differentiates it from competitors?',
        'lo.q.audience': 'Who is your target audience? (Ex: Moms, Athletes, Gamers)',
        'lo.q.problem': 'What problem does it solve for the customer?',
        'lo.q.usage': 'What is the main usage? (Ex: Daily, Gift, Travel)',
        'lo.processing.text': 'Perfect! I am creating your optimized listing now. This may take a few seconds...',
        'lo.success.text': 'Text listing generated successfully! Now, to finish, I need you to send a photo of the product (white background is ideal) so I can generate visual variations.',
        'lo.error.text': 'Oops, I had a problem generating the text. Please try again.',
        'lo.processing.image': 'Received the image! Generating 3 optimized variations...',
        'lo.success.image': 'Ready! Your listing is complete. See below.',
        'lo.error.image': 'Error generating images. But check the text below.',
        'lo.ui.assistant': 'Assistant',
        'lo.ui.history': 'History',
        'lo.ui.history.empty': 'No saved listings.',
        'lo.ui.upload': 'Click to upload photo',
        'lo.ui.input_placeholder': 'Type your answer...',
        'lo.ui.title': 'Your listing will appear here',
        'lo.ui.subtitle': 'Answer the questions so our AI can create a high-conversion listing.',
        'lo.ui.save': 'Save Listing',
        'lo.ui.generating_images': 'Generating Images...',
        'analyze.button': 'Analyze Competition',
        'analyze.modal_title': 'AI Competition Analysis',
        'analyze.weaknesses': 'Competitor Weaknesses',
        'analyze.improvements': 'Improvement Opportunities',
        'analyze.processing': 'Scraping reviews and analyzing with AI...',
        'analyze.error': 'Error analyzing competition.',
        'analyze.credits_info': 'Consumes 5 premium credits',
        'analyze.recent_reviews': 'Latest Reviews',
        'summary.feb_2026': 'Feb 2026',

        // Profit Simulator
        'sim.title': 'Real Profit Simulator',
        'sim.product_cost': 'Product Cost',
        'sim.product_cost_help': 'The price you pay your supplier per unit, including shipping to your warehouse.',
        'sim.tax_rate': 'Tax (%)',
        'sim.tax_rate_help': 'Your business tax rate (e.g., SIMPLES Nacional). Usually between 4% and 15% in Brazil.',
        'sim.op_expenses': 'Operational Expenses',
        'sim.op_expenses_help': 'Cost of packaging, labels, and prep service per unit.',
        'sim.ads_ppc': 'Ads Investment (PPC)',
        'sim.ads_ppc_help': 'How much you plan to spend on Amazon Advertising to get one sale. A safe start is 10-15% of the price.',
        'sim.total_expenses': 'Total Expenses',
        'sim.net_profit': 'Net Profit',
        'sim.net_margin': 'Net Margin',
        'sim.roi': 'ROI (Return)',
        'sim.fba_vs_fbm': 'Comparison FBA vs FBM',
        'sim.amazon_fulfilment': 'Amazon Fulfilment (FBA)',
        'sim.your_fulfilment': 'Your Fulfilment (FBM)',
        'sim.item_price': 'Item Price',
        'sim.delivery_charge': 'Delivery Charge',
        'sim.amazon_fees': 'Amazon Fees',
        'sim.referral_fee': 'Referral Fee',
        'sim.fulfilment_cost': 'Fulfilment Cost',
        'sim.storage_cost': 'Storage Cost',
        'sim.jan_sep': 'January-September',
        'sim.oct_dec': 'October-December',
        'sim.storage_per_unit': 'Monthly storage cost per unit',
        'sim.avg_inventory': 'Average inventory units stored',
        'sim.est_sales_month': 'Estimated monthly units sold',
        'sim.storage_per_sold': 'Storage cost per unit sold',
        'sim.fixed_closing': 'Fixed Closing Fee',
        'sim.variable_closing': 'Variable Closing Fee',
        'sim.digital_services': 'Digital Services Fee',
        'sim.misc_cost': 'Miscellaneous Cost',
        'sim.shipping_out': 'Delivery Charge',
        'sim.total_sales_price': 'Total Sales Price',
        'sim.other_costs': 'Other Costs',
        'sim.vat': 'VAT / Taxes',
        'sim.cogs': 'Cost of Goods Sold (COGS)',
        'sim.net_proceeds': 'Net Proceeds',
        'sim.search_placeholder': 'Search ASIN or Keyword...',
        'sim.search_button': 'Search Product',
        'sim.search_another': 'Search another product',
        'sim.export_pdf': 'Export PDF Report',

        // Profile & Billing
        'profile.title': 'Profile',
        'profile.change_password': 'Change Password',
        'profile.buy_credits': 'Buy Credits',
        'profile.change_plan': 'Change Plan',
        'profile.current_plan': 'Current Plan',
        'profile.admin_label': 'Administrator',
        'profile.pro_label': 'Pro Plan',
        'profile.welcome': 'Welcome',

        // Plans
        'plans.starter': 'Starter',
        'plans.starter_desc': 'Ideal for starting',
        'plans.starter_features': '5 Initial Credits',
        'plans.pro': 'Pro Plan',
        'plans.pro_desc': 'For growing sellers',
        'plans.pro_price': '29€/month',
        'plans.premium': 'Premium Plan',
        'plans.premium_desc': 'Full AI Power',
        'plans.premium_price': '49€/month',
        'plans.select': 'Select Plan',
        'plans.free': 'Free',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('pt');

    const t = (key: string): string => {
        // @ts-ignore
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
