import React, { createContext, useContext, useState, ReactNode, useEffect, useMemo } from 'react';
import { useAuth } from '../contexts/AuthContext';

export type Language = 'pt' | 'es' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

export const translations = {
    pt: {
        // General
        'app.title': 'Amazon Sem Segredos',
        'app.full_title': 'Amazon Sem Segredos IA Suite',
        'search.placeholder': 'Digite palavra-chave ou ASIN',
        'search.button': 'Pesquisar',
        'searching': 'Pesquisando...',
        'suppliers.link': 'Encontrar Fornecedores no Alibaba',
        'rows.selected': 'Linhas Selecionadas',
        'filter.results': 'Filtrar Resultados',
        'search.image_tooltip': 'Upload de Imagem',
        'search.camera_tooltip': 'Tirar Foto',
        'search.sources_title': 'Busca Rápida em Fontes',
        'maintenance.title': 'Sistema em Manutenção',
        'maintenance.desc': 'Estamos realizando melhorias na plataforma para oferecer uma experiência ainda melhor. Voltaremos em breve!',
        'maintenance.restricted': 'Acesso Restrito',
        'maintenance.back': 'Voltar ao Início',

        // Landing Page
        'nav.features': 'Funcionalidades',
        'nav.pricing': 'Preços',
        'nav.access': 'Acessar Plataforma',
        'hero.tag': 'Nova Ferramenta de Análise Inteligente',
        'hero.title': 'Pare de tentar vender. Comece a lucrar na Amazon com dados reais.',
        'hero.subtitle': 'Analise produtos, calcule taxas FBA com precisão cirúrgica e monitore a concorrência em segundos. Sem achismos, apenas lucro líquido.',
        'hero.cta': 'Começar análise gratuita agora',
        'problem.title': 'Taxas escondidas roubando seu lucro?',
        'problem.bad.title': 'Planilhas complexas que quebram',
        'problem.bad.desc': 'Horas perdidas atualizando taxas de FBA manualmente e torcendo para a fórmula estar certa.',
        'problem.good.tag': 'A Solução',
        'problem.good.title': 'Amazon Sem Segredos IA Suite',
        'problem.good.desc': 'Cálculo reverso em tempo real. Cole um ASIN e veja seu ROI e lucro líquido instantaneamente.',
        'features.title': 'Tudo o que você precisa para dominar a Buy Box',
        'features.subtitle': 'De pesquisa de produto à análise de variação, centralizado em uma única ferramenta premium.',
        'features.finder.title': 'Buscador de Produtos',
        'features.finder.desc': 'Encontre os melhores produtos para vender na Amazon com análise detalhada de taxas FBA, margem de lucro líquida e ROI em segundos.',
        'features.mentor.title': 'Mentor Virtual',
        'features.mentor.desc': 'Tire suas dúvidas 24/7 com nossa inteligência artificial treinada por especialistas para te auxiliar com estratégias, bloqueios e fornecedores europeus.',
        'features.sourcing.title': 'Busca de Fornecedores',
        'features.sourcing.desc': 'Pesquise por fornecedores verificados e marcas confiáveis para abastecer seu negócio e vender na Amazon Europa sem dor de cabeça.',
        'features.optimizer.title': 'Criador de Listing',
        'features.optimizer.desc': 'Crie títulos, bullet points e descrições otimizadas com IA, e gere imagens profissionais prontas para o padrão da Amazon.',
        'pricing.title': 'Planos que crescem com você',
        'pricing.subtitle': 'Escolha o plano ideal para o seu estágio na jornada Amazon FBA.',
        'pricing.free.name': 'Free',
        'pricing.free.price': '€0',
        'pricing.free.f1': '30 créditos iniciais',
        'pricing.free.f2': 'Análise básica',
        'pricing.free.f3': 'Suporte por email',
        'pricing.free.f4': '', // Not used in free
        'pricing.free.cta': 'Começar Grátis',
        'pricing.starter.name': 'Starter',
        'pricing.starter.price': '€19',
        'pricing.starter.f1': '90 créditos/mês',
        'pricing.starter.f2': 'Análise básica',
        'pricing.starter.f3': 'Criador de Anúncios Avançado',
        'pricing.starter.f4': 'Suporte por e-mail',
        'pricing.starter.cta': 'Selecionar Plano',
        'pricing.pro.name': 'Pro',
        'pricing.pro.price': '€49',
        'pricing.pro.f1': '200 créditos/mês',
        'pricing.pro.f2': 'Análise profunda com IA',
        'pricing.pro.f3': 'Criador de Anúncios Pro',
        'pricing.pro.f4': 'Suporte por e-mail e WhatsApp',
        'pricing.pro.recommended': 'Recomendado',
        'pricing.pro.cta': 'Selecionar Plano',
        'pricing.premium.name': 'Premium',
        'pricing.premium.price': '€99',
        'pricing.premium.f1': '600 créditos/mês',
        'pricing.premium.f2': 'Análise profunda com IA',
        'pricing.premium.f3': 'Criador de Anúncios Pro',
        'pricing.premium.f4': 'Suporte por e-mail e WhatsApp',
        'pricing.premium.f5': 'Mentoria Exclusiva (VIP)',
        'pricing.premium.cta': 'Selecionar Plano',
        'footer.rights': 'Todos os direitos reservados.',

        // Support
        'support.widget_title': 'Central de Suporte',
        'support.modal_title': 'Central de Suporte',
        'support.modal_subtitle': 'Como podemos ajudar você hoje?',
        'support.vip_title': 'Suporte VIP WhatsApp',
        'support.vip_desc': 'Atendimento prioritário para você.',
        'support.whatsapp_button': 'Chamar no WhatsApp',
        'support.whatsapp_text': 'Olá! Gostaria de uma ajuda com a plataforma Amazon Sem Segredos IA Suite.',
        'support.or_ticket': 'Ou envie um ticket abaixo',
        'support.subject_label': 'Assunto',
        'support.subject_placeholder': 'Resumo do problema',
        'support.message_label': 'Mensagem',
        'support.message_placeholder': 'Descreva seu problema ou dúvida em detalhes...',
        'support.cancel': 'Cancelar',
        'support.send': 'Enviar Ticket',
        'support.sending': 'Enviando...',
        'support.success_title': 'Ticket Enviado!',
        'support.success_desc': 'Nossa equipe recebeu sua mensagem e responderá em breve.',
        'support.error_default': 'Houve um erro de comunicação. Tente novamente.',
        'support.error_send': 'Erro ao enviar ticket.',
        'profile.user_placeholder': 'Usuário',
        'profile.upgrade': 'Fazer Upgrade',
        'profile.credits': 'Créditos',
        'ads.premium_desc': 'Este módulo utiliza Reinforcement Learning para otimizar seus lances e palavras-chave automaticamente. Disponível no plano Premium.',
        'checkout.error_base': 'Erro ao iniciar checkout. Tente novamente.',
        'checkout.error_conn': 'Erro de conexão. Verifique sua internet.',
        'common.cancel': 'Cancelar',
        'sidebar.tools': 'Ferramentas',
        'common.unit': 'unidade',
        'common.product': 'Produto',

        // Product Finder Headers
        'col.product_details': 'Detalhes do Produto',
        'col.asin': 'ASIN',
        'col.brand': 'Marca',
        'col.price': 'Preço',
        'col.sales': 'Vendas',
        'col.sales_graph': 'Gráfico de Vendas',
        'col.ranking_bsr': 'Ranking (BSR)',
        'col.revenue': 'Receita',
        'col.bsr': 'BSR',
        'col.fba_fees': 'Taxas FBA',
        'col.active_sellers': 'Vendedores Ativos',

        // Summary Cards
        'summary.search_volume': 'Volume de Busca',
        'summary.total_revenue': 'Receita Total',
        'summary.avg_revenue': 'Receita Média',
        'summary.avg_price': 'Preço Médio',
        'summary.avg_bsr': 'BSR Médio',
        'summary.avg_reviews': 'Avaliações Médias',
        'summary.success_score': 'Pontuação de Sucesso',

        // Empty States / Errors
        'error.no_products': 'Nenhum produto encontrado. Inicie uma pesquisa.',
        'error.insufficient_credits': 'Créditos insuficientes. Por favor, recarregue seu saldo.',
        'error.internal_server': 'Erro interno. Tente novamente mais tarde.',
        'error.search_failed': 'Erro ao buscar o produto. Verifique sua conexão ou tente novamente.',
        'error.checkout_failed': 'Erro ao iniciar checkout. Tente novamente.',
        'error.connection': 'Erro de conexão. Verifique sua internet.',

        // Product Categories
        'category.Beauty': 'Beleza',
        'category.Electronics': 'Eletrônicos',
        'category.Home': 'Casa',
        'category.Kitchen': 'Cozinha',
        'category.Toys': 'Brinquedos',
        'category.Sports': 'Esportes',
        'category.Unknown': 'Geral',

        // Modules
        'module.dashboard': 'Visão Geral',
        'module.mentor': 'Mentor Virtual',
        'module.product_finder': 'Buscador de Produtos',
        'module.supplier_finder': 'Fornecedores',
        'module.profit_calculator': 'Calculadora de Lucro Real',
        'module.listing_optimizer': 'Criador de Listing',
        'module.ads_manager': 'Gerenciador de Ads',
        'module.settings': 'Configurações',
        'module.account': 'Minha Conta',
        'module.logout': 'Sair',
        'auth.forgot_password': 'Esqueci minha senha',
        'auth.reset_password': 'Redefinir Senha',
        'auth.back_to_login': 'Voltar para Login',
        'auth.send_reset_link': 'Enviar Link de Recuperação',
        'auth.reset_email_sent': 'Link de recuperação enviado! Verifique seu e-mail.',

        // Profile & Billing
        'profile.title': 'Perfil',
        'profile.change_password': 'Trocar Senha',
        'profile.buy_credits': 'Comprar Créditos',
        'profile.change_plan': 'Trocar de Plano',
        'profile.current_plan': 'Plano Atual',
        'profile.admin_label': 'Administrador',
        'profile.pro_label': 'Plano Pro',
        'profile.welcome': 'Bem-vindo',
        'profile.credits_label': 'Créditos',

        // Plans
        'plans.starter': 'Starter',
        'plans.starter_desc': 'Ideal para começar',
        'plans.starter_features': '5 Créditos Iniciais',
        'plans.pro': 'Plano Pro',
        'plans.pro_desc': 'Para vendedores em crescimento',
        'plans.pro_price': '29€/mês',
        'plans.premium': 'Plano Premium',
        'plans.premium_desc': 'Poder total da IA',
        'plans.premium_price': '49€/mês',
        'plans.select': 'Escolher Plano',
        'plans.free': 'Grátis',
        'plans.upgrade': 'Fazer Upgrade',

        'modal.details': 'Detalhes',
        'modal.est_sales': 'Vendas Est.',
        'modal.est_revenue': 'Receita Est.',
        'modal.price': 'Preço',
        'modal.sellers': 'Vendedores',
        'modal.reviews': 'Avaliações',
        'modal.score': 'Score',
        'modal.fba_fees': 'Taxas FBA',
        'modal.view_amazon': 'Ver na Amazon',
        'modal.units_month': 'Unid. / Mês',
        'modal.footer_disclaimer': 'Dados fornecidos pela Amazon SP-API • Estimativas baseadas na categoria',
        'modal.unknown_brand': 'Marca Desconhecida',
        'mentor.title': 'Conheça nossos 9 Agentes Especializados',
        'mentor.subtitle': 'Cada um é preparado para lidar com desafios específicos.',

        // Listing Optimizer
        'lo.intro': 'Olá! Sou seu especialista em Amazon. Vamos criar um anúncio vencedor para a Amazon? Primeiro, qual é o nome do seu produto?',
        'lo.q.productName': 'Qual é o nome do seu produto?',
        'lo.q.category': 'Qual a categoria dele? (Ex: Cozinha, Esportes, Eletrônicos)',
        'lo.q.material': 'De qual material ele é feito? (Ex: Aço Inox, Algodão Orgânico)',
        'lo.q.benefits': 'Quais são os principais benefícios? (Liste 2 ou 3)',
        'lo.q.differentiators': 'O que o diferencia dos concorrentes? (Seu diferencial)',
        'lo.q.audience': 'Quem é o seu público-alvo? (Ex: Mães, Atletas, Gamers)',
        'lo.q.problem': 'Que problema ele resolve para o cliente?',
        'lo.q.usage': 'Qual o uso principal? (Ex: Dia a dia, Presente, Viagem)',
        'lo.processing.text': 'Perfeito! Estou criando seu anúncio otimizado agora. Isso pode levar alguns segundos...',
        'lo.success.text': 'Anúncio de texto gerado com sucesso! Agora, para finalizar, preciso que você envie uma foto do produto (fundo branco é ideal) para que eu possa gerar variações visuais.',
        'lo.error.text': 'Ops, tive um problema ao gerar o texto. Tente novamente.',
        'lo.processing.image': 'Recebi a imagem! Estou gerando variações otimizadas para o anúncio...',
        'lo.success.image': 'Pronto! Seu anúncio está completo. Veja abaixo.',
        'lo.error.image': 'Erro ao gerar imagens. Envie uma imagem valida',
        'lo.ui.assistant': 'Assistente',
        'lo.ui.history': 'Histórico',
        'lo.ui.history.empty': 'Nenhum listing salvo.',
        'lo.ui.upload': 'Clique para enviar foto',
        'lo.ui.input_placeholder': 'Digite sua resposta...',
        'lo.ui.title': 'Seu anúncio aparecerá aqui',
        'lo.ui.subtitle': 'Responda as perguntas ao lado para que nossa IA crie um anúncio de alta conversão para seu produto.',
        'lo.ui.save': 'Salvar Listing',
        'lo.ui.generating_images': 'Gerando Imagens...',
        'lo.ui.title_label': 'Título do Anúncio',
        'lo.ui.bullets_label': 'Pontos Importantes',
        'lo.ui.desc_label': 'Descrição do Produto',
        'lo.ui.keywords_label': 'Palavras-Chave de Busca',
        'lo.ui.benefits_summary': 'Resumo de Benefícios',
        'mentor.placeholder': 'Pergunte qualquer coisa ao seu mentor...',
        'mentor.unclear': 'Não consegui entender, pode repetir?',
        'mentor.specialized': 'Agente Especializado',
        'mentor.you': 'Você',
        'mentor.video_rec': 'Vídeo Recomendado pelo Mentor',
        'mentor.access_tool': 'Acessar Ferramenta',
        'mentor.analyzing': 'Analisando...',
        'pf.title_unavailable': 'Título Indisponível',
        'pf.est_sales_month': 'unidades estimadas / mês',
        'pf.avg_net_margin': 'Margem Líquida Média',
        'pf.price_fba_fees': 'Preço - Taxas FBA',
        'pf.comp_level': 'Nível de Competição',
        'pf.active_sellers_per_listing': 'sellers ativos por listing',
        'pf.empty_title': 'Onde está o lucro hoje?',
        'pf.empty_desc': 'Cole um ASIN ou pesquise por palavra-chave para começar a descobrir produtos altamente lucrativos.',
        'pf.first_search': 'Fazer Primeira Busca',
        'pf.loading_more': 'Carregando...',
        'pf.load_more': 'Carregar Mais Resultados',
        'pf.no_more': 'Fim dos Resultados',
        'sim.asin_error': 'Por favor, insira um ASIN válido (ex: B086PHS2V8). A calculadora aceita apenas ASINs.',
        'sim.search_failed': 'Erro ao buscar produto na Amazon.',
        'sim.report_title': 'Relatório Estratégico AI',
        'sim.generated_at': 'Gerado em',
        'sim.suite_name': 'Amazon Sem Segredos IA Suite',
        'sim.analyzed_product': 'Produto Analisado',
        'sim.no_product_search': 'Nenhum produto pesquisado. Análise baseada nos valores manuais inseridos.',
        'sim.fba_title': 'Logística da Amazon (FBA)',
        'sim.fbm_title': 'Logística do Vendedor (FBM)',
        'sim.break_even_desc': 'Preço mínimo para não ter prejuízo considerando todos os custos atuais.',
        'sim.fbm_break_even_desc': 'Considerando seus custos de logística própria e frete de envio.',
        'sim.fba_ads_impact_desc': 'Custo médio de publicidade gasto para vender uma unidade. Impacta diretamente sua margem líquida.',
        'sim.edit_costs': 'Editar discriminação dos custos',
        'sim.fbm_storage_hint': 'Insira os seus custos de armazenamento',
        'sim.simulate_rentability': 'Simule a Rentabilidade Real',
        'sim.simulate_desc': 'Cole um ASIN Amazon acima para analisar todas as taxas FBA, Margem Líquida e ROI em segundos.',
        'sim.iva_taxes': 'IVA / Impostos',
        'sup.title': 'Fornecedores',
        'sup.subtitle': 'Encontre os melhores parceiros para o seu negócio na Europa.',
        'sup.search_placeholder': 'Buscar por nome, produto ou nicho...',
        'sup.visit_site': 'Visitar Site',
        'sup.empty_title': 'Nenhum fornecedor encontrado',
        'sup.empty_desc': 'Tente mudar os filtros ou buscar por outros termos.',
        'sup.clear_filters': 'Limpar filtros',
        'cat.all': 'Todas',
        'cat.general': 'Geral',
        'cat.home_kitchen': 'Casa & Cozinha',
        'cat.toys_geek': 'Brinquedos & Geek',
        'cat.electronics': 'Eletrônicos',
        'cat.beauty_health': 'Beleza & Saúde',
        'cat.fashion_kids': 'Moda & Infantil',
        'cat.parties': 'Festas',
        'cat.tools_diy': 'Ferramentas & Bricolagem',
        'cat.baby': 'Bebê',
        'cat.decor': 'Decoração',
        'cat.dynamic.retailer': 'Varejista (B2C)',
        'cat.dynamic.wholesale': 'Atacadista (B2B)',
        'cat.dynamic.b2b': 'B2B',
        'cat.dynamic.b2c': 'B2C',
        'cat.dynamic.retailer_b2b': 'Varejo & Atacado',
        'analyze.button': 'Analisar Concorrência',
        'analyze.modal_title': 'Análise de Concorrência IA',
        'analyze.weaknesses': 'Fraquezas da Concorrência',
        'analyze.improvements': 'Oportunidades de Melhoria',
        'analyze.processing': 'Extraindo reviews e analisando com IA...',
        'analyze.error': 'Erro ao analisar concorrência.',
        'analyze.credits_info': 'Consome 1 crédito premium',
        'analyze.recent_reviews': 'Últimos Reviews',
        'summary.feb_2026': 'Fev 2026',
        'sim.pdf_recs_title': 'Recomendações Estratégicas',
        'lock.title': 'Limite de Créditos Atingido',

        // Profit Simulator
        'sim.title': 'Simulador de Lucro Real',
        'sim.product_cost': 'Custo do Produto',
        'sim.product_cost_help': 'O preço que você paga ao seu fornecedor por unidade, incluindo o frete até o seu armazém.',
        'sim.tax_rate': 'Imposto (%)',
        'sim.tax_rate_help': 'A alíquota de imposto do seu negócio (ex: SIMPLES Nacional). Geralmente entre 4% e 15% no Brasil.',
        'sim.op_expenses': 'Despesas Operacionais',
        'sim.op_expenses_help': 'Custo de embalagem, etiquetas e serviço de preparação por unidade.',
        'sim.ads_ppc': 'Investimento em Ads (PPC)',
        'sim.ads_ppc_help': 'Quanto você planeja gastar em Amazon Advertising para obter uma venda. Um começo seguro é entre 10-15% do preço.',
        'sim.total_expenses': 'Total de Despesas',
        'sim.net_profit': 'Lucro Líquido',
        'sim.net_margin': 'Margem Líquida',
        'sim.roi': 'ROI (Retorno)',
        'sim.export_pdf': 'Exportar Relatório PDF',
        'sim.fba_vs_fbm': 'Comparação FBA vs FBM',
        'sim.amazon_fulfilment': 'Logística da Amazon (FBA)',
        'sim.your_fulfilment': 'Sua Logística (FBM)',
        'sim.item_price': 'Preço do Item',
        'sim.delivery_charge': 'Taxa de Entrega',
        'sim.amazon_fees': 'Taxas da Amazon',
        'sim.referral_fee': 'Taxa de Indicação',
        'sim.fulfilment_cost': 'Custo de Logística',
        'sim.storage_cost': 'Custo de Armazenamento',
        'sim.jan_sep': 'Janeiro-Setembro',
        'sim.oct_dec': 'Outubro-Dezembro',
        'sim.storage_per_unit': 'Custo mensal de armazenamento por unidade',
        'sim.avg_inventory': 'Estoque Médio',
        'sim.est_sales_month': 'Vendas Estimadas / Mês',
        'sim.storage_per_sold': 'Armazenamento por unidade vendida',
        'sim.fixed_closing': 'Taxa fixa de fechamento',
        'sim.variable_closing': 'Taxa variável de fechamento',
        'sim.digital_services': 'Taxas de serviços digitais',
        'sim.misc_cost': 'Custo Diverso',
        'sim.shipping_out': 'Custo de envio ao cliente',
        'sim.total_sales_price': 'Preço total de venda',
        'sim.other_costs': 'Outros Custos',
        'sim.vat': 'IVA / Impostos',
        'sim.cogs': 'COGS (Custo Fornec.)',
        'sim.net_proceeds': 'Receita Líquida',
        'sim.search_placeholder': 'Insira o ASIN do produto (ex: B086PHS2V8)',
        'sim.search_button': 'Buscar Produto',
        'sim.search_another': 'Pesquisar outro produto',
        'sim.break_even': 'Break-even',
        'sim.ads_impact': 'Impacto de Ads',
        'sim.ads_cost_unit': 'Investimento em Ads / un.',
        'sim.acos_sim': 'Simulação de ACOS (%)',
        'sim.ai_advice': 'Conselho da IA',
        'sim.target_margin': 'Margem Alvo (%)',
        'sim.profit_per_lot': 'Lucro Estimado por Lote',
        'sim.strategy_fbm_title': 'Estratégia FBM',
        'sim.pdf_footer': 'Relatório gerado pela Amazon Sem Segredos IA Suite | IVA: {taxRate}% | Os valores são estimativas e podem variar.',
        'sim.batch': 'Lote',
        'sim.units_abbr': 'Unid.',
        'sim.labor': 'Mão de Obra',
        'sim.material': 'Material',
        'sim.inbound': 'Envio p/ Amazon',
        'sim.strategy_advice': 'Impacto de Ads & Estratégia',
        'sim.iva': 'IVA / Impostos',
        'sim.weight': 'Peso',
        'sim.sales_rank': 'BSR (Sales Rank)',
        'sourcing.title': 'Buscar Fornecedores',
        'sourcing.desc': 'Pesquisamos automaticamente fornecedores de atacado para este produto.',
        'sourcing.alibaba': 'Buscar no Alibaba (Atacado)',
        'sourcing.aliexpress': 'Buscar no AliExpress',
        'sourcing.1688': 'Buscar no 1688 (Fábricas)',
        'sourcing.google_lens': 'Pesquisa Visual (Google)',
        'sourcing.find_suppliers': 'Encontrar Fornecedores',
        'sourcing.estimated_cost': 'Custo Sugerido por IA',
        'sourcing.rule_of_thumb': '* Estimativa baseada na regra de ouro de 30% do preço de venda para produtos private label. Verifique sempre com fornecedores reais.',
        'pf.emerging': 'Emergente',
        'pf.units_month': 'unidades/mês',
        'pf.bsr_tool_tip': 'BSR não disponível no momento. Interesse de mercado estimado via volume de busca mensal.',
        'pf.bsr_unavailable_tip': 'BSR indisponível. Vendas estimadas baseadas no interesse de mercado.',
        'pf.sales_census_tip': 'Vendas estimadas nos últimos 30 dias baseadas no Censo BSR 2025 para {category}.',
        'pf.top_percentile_tip': 'Este produto está entre os top {total} itens da categoria {category} (Baseado no Censo 2025).',
        'pf.price_fallback_tip': 'Preço baseado na menor oferta disponível (Professional Seller)',
        'pf.msrp_tip': 'Preço de Tabela (MSRP). O preço real de venda pode ser menor.',
        'pf.fba_breakdown_tip': 'Referral ({rate}%): {referral} | Fulfillment: {fulfillment}{estimate}',
        'pf.opportunity_score': 'Opportunity Score',
        'pf.opportunity_score_desc': '% de produtos Top 1% ou 3%',
        'pf.filter': 'Filtrar',
        'pf.brand': 'Marca',
        'pf.min_price': 'Preço Mín',
        'pf.max_price': 'Preço Máx',
        'pf.clear_filters': 'Limpar Filtros',
        'pf.selected_analysis': 'Análise de Itens Selecionados',
    },
    es: {
        // General
        'app.title': 'Amazon Sem Segredos IA Suite',
        'app.full_title': 'Amazon Sem Segredos IA Suite',
        'search.placeholder': 'Ingrese palabra clave o ASIN',
        'search.button': 'Buscar',
        'searching': 'Buscando...',
        'suppliers.link': 'Encontrar Proveedores en Alibaba',
        'rows.selected': 'Filas Seleccionadas',
        'filter.results': 'Filtrar Resultados',
        'search.image_tooltip': 'Subir Imagen',
        'search.camera_tooltip': 'Tomar Foto',
        'search.sources_title': 'Búsqueda Rápida en Fuentes',
        'maintenance.title': 'Sistema en Mantenimiento',
        'maintenance.desc': 'Estamos realizando mejoras en la plataforma para ofrecer una experiencia aún mejor. ¡Volveremos pronto!',
        'maintenance.restricted': 'Acceso Restringido',
        'maintenance.back': 'Volver al Inicio',

        // Landing Page
        'nav.features': 'Funcionalidades',
        'nav.pricing': 'Precios',
        'nav.access': 'Acceder a la Plataforma',
        'hero.tag': 'Nueva Herramienta de Análisis Inteligente',
        'hero.title': 'Deja de intentar vender. Comienza a lucrar en Amazon con datos reales.',
        'hero.subtitle': 'Analiza productos, calcula tarifas FBA con precisión quirúrgica y monitorea a la competencia en segundos. Sin suposiciones, solo beneficio neto.',
        'hero.cta': 'Comenzar análisis gratuito ahora',
        'problem.title': '¿Tarifas ocultas robando tu beneficio?',
        'problem.bad.title': 'Planillas complejas que fallan',
        'problem.bad.desc': 'Horas perdidas actualizando tarifas de FBA manualmente y esperando que la fórmula sea correcta.',
        'problem.good.tag': 'La Solución',
        'problem.good.title': 'Amazon Sem Segredos IA Suite',
        'problem.good.desc': 'Cálculo inverso en tiempo real. Pega un ASIN y ve tu ROI y beneficio neto instantáneamente.',
        'features.title': 'Todo lo que necesitas para dominar la Buy Box',
        'features.subtitle': 'Desde investigación de producto hasta análisis de variación, centralizado en una única herramienta premium.',
        'features.finder.title': 'Buscador de Productos',
        'features.finder.desc': 'Encuentra los mejores productos para vender en Amazon con análisis detallado de tarifas FBA, margen de beneficio neto y ROI en segundos.',
        'features.mentor.title': 'Mentor Virtual',
        'features.mentor.desc': 'Resuelve tus dudas 24/7 con nuestra inteligencia artificial entrenada por expertos para ayudarte con estrategias, bloqueos y proveedores europeos.',
        'features.sourcing.title': 'Búsqueda de Proveedores',
        'features.sourcing.desc': 'Busca proveedores verificados y marcas confiables para abastecer tu negocio y vender en Amazon Europa sin complicaciones.',
        'features.optimizer.title': 'Creador de Listados',
        'features.optimizer.desc': 'Crea títulos, bullet points y descripciones optimizadas con IA, y genera imágenes profesionales listas para el estándar de Amazon.',
        'pricing.title': 'Planes que crecen contigo',
        'pricing.subtitle': 'Elige el plan ideal para tu etapa en el viaje de Amazon FBA.',
        'pricing.free.name': 'Gratis',
        'pricing.free.price': '€0',
        'pricing.free.f1': '30 créditos iniciales',
        'pricing.free.f2': 'Análisis básico',
        'pricing.free.f3': 'Soporte por email',
        'pricing.free.f4': '',
        'pricing.free.cta': 'Comenzar Gratis',
        'pricing.starter.name': 'Starter',
        'pricing.starter.price': '€19',
        'pricing.starter.f1': '90 créditos/mes',
        'pricing.starter.f2': 'Análisis básico',
        'pricing.starter.f3': 'Creador de Anuncios Avanzado',
        'pricing.starter.f4': 'Soporte por email',
        'pricing.starter.cta': 'Seleccionar Plan',
        'pricing.pro.name': 'Pro',
        'pricing.pro.price': '€49',
        'pricing.pro.f1': '200 créditos/mes',
        'pricing.pro.f2': 'Análisis profundo con IA',
        'pricing.pro.f3': 'Creador de Anuncios Pro',
        'pricing.pro.f4': 'Soporte por email y WhatsApp',
        'pricing.pro.recommended': 'Recomendado',
        'pricing.pro.cta': 'Seleccionar Plan',
        'pricing.premium.name': 'Premium',
        'pricing.premium.price': '€99',
        'pricing.premium.f1': '600 créditos/mes',
        'pricing.premium.f2': 'Análisis profundo con IA',
        'pricing.premium.f3': 'Creador de Anuncios Pro',
        'pricing.premium.f4': 'Soporte por email y WhatsApp',
        'pricing.premium.f5': 'Mentoría Exclusiva (VIP)',
        'pricing.premium.cta': 'Seleccionar Plan',
        'footer.rights': 'Todos los derechos reservados.',

        // Support
        'support.widget_title': 'Centro de Soporte',
        'support.modal_title': 'Centro de Soporte',
        'support.modal_subtitle': '¿Cómo podemos ayudarte hoy?',
        'support.vip_title': 'Soporte VIP WhatsApp',
        'support.vip_desc': 'Atención prioritaria para ti.',
        'support.whatsapp_button': 'Llamar por WhatsApp',
        'support.whatsapp_text': '¡Hola! Me gustaría ayuda con la plataforma Amazon Sem Segredos IA Suite.',
        'support.or_ticket': 'O envía un ticket a continuación',
        'support.subject_label': 'Asunto',
        'support.subject_placeholder': 'Resumen del problema',
        'support.message_label': 'Mensaje',
        'support.message_placeholder': 'Describe tu problema o duda en detalle...',
        'support.cancel': 'Cancelar',
        'support.send': 'Enviar Ticket',
        'support.sending': 'Enviando...',
        'support.success_title': '¡Ticket Enviado!',
        'support.success_desc': 'Nuestro equipo ha recibido tu mensaje y responderá pronto.',
        'support.error_default': 'Hubo un error de comunicación. Inténtalo de nuevo.',
        'support.error_send': 'Error al enviar el ticket.',
        'profile.user_placeholder': 'Usuario',
        'profile.upgrade': 'Mejorar Plan',
        'profile.credits': 'Créditos',
        'ads.premium_desc': 'Este módulo utiliza Reinforcement Learning para optimizar sus ofertas y palabras clave automáticamente. Disponible en el plan Premium.',
        'checkout.error_base': 'Error al iniciar el pago. Inténtelo de nuevo.',
        'checkout.error_conn': 'Error de conexión. Verifique su internet.',
        'common.cancel': 'Cancelar',
        'sidebar.tools': 'Herramientas',
        'common.unit': 'unidad',
        'common.product': 'Producto',

        // Product Finder Headers
        'col.product_details': 'Detalles del Producto',
        'col.asin': 'ASIN',
        'col.brand': 'Marca',
        'col.price': 'Precio',
        'col.sales': 'Ventas',
        'col.sales_graph': 'Gráfico de Ventas',
        'col.ranking_bsr': 'Clasificación (BSR)',
        'col.revenue': 'Ingresos',
        'col.bsr': 'BSR',
        'col.fba_fees': 'Tarifas FBA',
        'col.active_sellers': 'Vendedores Activos',

        // Summary Cards
        'summary.search_volume': 'Volumen de Búsqueda',
        'summary.total_revenue': 'Ingresos Totales',
        'summary.avg_revenue': 'Ingresos Promedio',
        'summary.avg_price': 'Precio Promedio',
        'summary.avg_bsr': 'BSR Promedio',
        'summary.avg_reviews': 'Reseñas Promedio',
        'summary.success_score': 'Puntuación de Éxito',

        // Empty States / Errors
        'error.no_products': 'No se encontraron productos. Inicie una búsqueda.',
        'error.insufficient_credits': 'Créditos insuficientes. Por favor, recarga tu saldo.',
        'error.internal_server': 'Error interno. Inténtalo de nuevo más tarde.',
        'error.search_failed': 'Error al buscar el producto. Verifica tu conexión o inténtalo de nuevo.',
        'error.checkout_failed': 'Error al iniciar el pago. Inténtalo de nuevo.',
        'error.connection': 'Error de conexión. Verifica tu internet.',

        // Product Categories
        'category.Beauty': 'Belleza',
        'category.Electronics': 'Electrónica',
        'category.Home': 'Hogar',
        'category.Kitchen': 'Cocina',
        'category.Toys': 'Juguetes',
        'category.Sports': 'Deportes',
        'category.Unknown': 'General',

        // Modules
        'module.dashboard': 'Visión General',
        'module.mentor': 'Mentor Virtual',
        'module.product_finder': 'Buscador de Productos',
        'module.supplier_finder': 'Proveedores',
        'module.profit_calculator': 'Calculadora de Beneficio Real',
        'module.listing_optimizer': 'Optimizador de Listados',
        'module.ads_manager': 'Gestor de Anuncios',
        'module.settings': 'Configuración',
        'module.account': 'Mi Cuenta',
        'module.logout': 'Cerrar Sesión',
        'auth.forgot_password': 'Olvidé mi contraseña',
        'auth.reset_password': 'Restablecer Contraseña',
        'auth.back_to_login': 'Volver al Login',
        'auth.send_reset_link': 'Enviar Enlace de Recuperación',
        'auth.reset_email_sent': '¡Enlace de recuperación enviado! Revisa tu correo electrónico.',

        // Profile & Billing
        'profile.title': 'Perfil',
        'profile.change_password': 'Cambiar Contraseña',
        'profile.buy_credits': 'Comprar Créditos',
        'profile.change_plan': 'Cambiar de Plan',
        'profile.current_plan': 'Plan Actual',
        'profile.admin_label': 'Administrador',
        'profile.pro_label': 'Plan Pro',
        'profile.welcome': 'Bienvenido',
        'profile.credits_label': 'Créditos',

        // Plans
        'plans.starter': 'Starter',
        'plans.starter_desc': 'Ideal para comenzar',
        'plans.starter_features': '5 Créditos Iniciales',
        'plans.pro': 'Plan Pro',
        'plans.pro_desc': 'Para vendedores en crecimiento',
        'plans.pro_price': '29€/mês',
        'plans.premium': 'Plan Premium',
        'plans.premium_desc': 'Poder total de la IA',
        'plans.premium_price': '49€/mês',
        'plans.select': 'Seleccionar Plan',
        'plans.free': 'Gratis',
        'plans.upgrade': 'Hacer Upgrade',

        'modal.details': 'Detalles',
        'modal.est_sales': 'Ventas Est.',
        'modal.est_revenue': 'Ingresos Est.',
        'modal.price': 'Precio',
        'modal.sellers': 'Vendedores',
        'modal.reviews': 'Reseñas',
        'modal.score': 'Puntuación',
        'modal.fba_fees': 'Tarifas FBA',
        'modal.view_amazon': 'Ver en Amazon',
        'modal.units_month': 'Unid. / Mes',
        'modal.footer_disclaimer': 'Datos proporcionados por Amazon SP-API • Estimaciones basadas en la categoría',
        'modal.unknown_brand': 'Marca Desconocida',
        'mentor.title': 'Conozca nuestros 9 Agentes Especializados',
        'mentor.subtitle': 'Cada uno está preparado para enfrentar desafíos específicos.',

        // Listing Optimizer
        'lo.intro': '¡Hola! Soy tu experto en Amazon. ¿Vamos a crear un anuncio ganador para Amazon? Primero, ¿cuál es el nombre de tu producto?',
        'lo.q.productName': '¿Cuál es el nombre de tu producto?',
        'lo.q.category': '¿Cuál es su categoría? (Ej: Cocina, Deportes, Electrónica)',
        'lo.q.material': '¿De qué material está hecho? (Ej: Acero Inoxidable, Algodón Orgánico)',
        'lo.q.benefits': '¿Cuáles son los principales beneficios? (Lista 2 o 3)',
        'lo.q.differentiators': '¿Qué lo diferencia de la competencia? (Tu diferencial)',
        'lo.q.audience': '¿Quién es tu público objetivo? (Ej: Madres, Atletas, Gamers)',
        'lo.q.problem': '¿Qué problema resuelve para el cliente?',
        'lo.q.usage': '¿Cuál es el uso principal? (Ej: Diario, Regalo, Viaje)',
        'lo.processing.text': '¡Perfecto! Estoy creando tu anuncio optimizado ahora. Esto puede tardar unos segundos...',
        'lo.success.text': '¡Anuncio de texto generado con éxito! Ahora, para finalizar, necesito que envíes una foto del producto (fondo blanco es ideal) para generar variaciones visuales.',
        'lo.error.text': 'Ups, tuve un problema al generar el texto. Inténtalo de nuevo.',
        'lo.processing.image': '¡Recibí la imagen! Estoy generando variaciones optimizadas para el anuncio...',
        'lo.success.image': '¡Listo! Tu anuncio está completo. Mira abajo.',
        'lo.error.image': 'Error al generar imágenes. Envie una imagen válida',
        'lo.ui.assistant': 'Asistente',
        'lo.ui.history': 'Historial',
        'lo.ui.history.empty': 'Ningún listado guardado.',
        'lo.ui.upload': 'Clic para enviar foto',
        'lo.ui.input_placeholder': 'Escribe tu respuesta...',
        'lo.ui.title': 'Tu anuncio aparecerá aquí',
        'lo.ui.subtitle': 'Responde las preguntas para que nuestra IA cree un anuncio de alta conversión para tu producto.',
        'lo.ui.save': 'Guardar Listado',
        'lo.ui.generating_images': 'Generando Imágenes...',
        'lo.ui.title_label': 'Título del Anuncio',
        'lo.ui.bullets_label': 'Puntos Importantes',
        'lo.ui.desc_label': 'Descripción del Producto',
        'lo.ui.keywords_label': 'Palabras Clave de Búsqueda',
        'lo.ui.benefits_summary': 'Resumen de Beneficios',
        'mentor.placeholder': 'Pregunta lo que quieras a tu mentor...',
        'mentor.unclear': 'No pude entender, ¿puedes repetir?',
        'mentor.specialized': 'Agente Especializado',
        'mentor.you': 'Tú',
        'mentor.video_rec': 'Video Recomendado por el Mentor',
        'mentor.access_tool': 'Acceder a Herramienta',
        'mentor.analyzing': 'Analizando...',
        'pf.title_unavailable': 'Título No Disponible',
        'pf.est_sales_month': 'unidades estimadas / mes',
        'pf.avg_net_margin': 'Margen Neto Promedio',
        'pf.price_fba_fees': 'Precio - Tarifas FBA',
        'pf.comp_level': 'Nivel de Competición',
        'pf.active_sellers_per_listing': 'vendedores activos por listado',
        'pf.empty_title': '¿Dónde está el beneficio hoy?',
        'pf.empty_desc': 'Pega un ASIN o busca por palabra clave para empezar a descubrir productos altamente rentables.',
        'pf.first_search': 'Hacer Primera Búsqueda',
        'pf.loading_more': 'Cargando...',
        'pf.load_more': 'Cargar Más Resultados',
        'pf.no_more': 'Fin de los Resultados',
        'sim.asin_error': 'Por favor, ingrese un ASIN válido (ej: B086PHS2V8). La calculadora solo acepta ASINs.',
        'sim.search_failed': 'Error al buscar el producto en Amazon.',
        'sim.report_title': 'Informe Estratégico AI',
        'sim.generated_at': 'Generado el',
        'sim.suite_name': 'Amazon Sem Segredos IA Suite',
        'sim.analyzed_product': 'Producto Analizado',
        'sim.no_product_search': 'Ningún producto buscado. Análisis basado en los valores manuales ingresados.',
        'sim.fba_title': 'Logística de Amazon (FBA)',
        'sim.fbm_title': 'Logística del Vendedor (FBM)',
        'sim.break_even_desc': 'Precio mínimo para no tener pérdidas considerando todos los costos actuales.',
        'sim.fbm_break_even_desc': 'Considerando sus costos de logística propia y flete de envío.',
        'sim.fba_ads_impact_desc': 'Costo promedio de publicidad gastado para vender una unidad. Impacta directamente su margen neto.',
        'sim.edit_costs': 'Editar desglose de costos',
        'sim.fbm_storage_hint': 'Ingrese sus costos de almacenamiento',
        'sim.simulate_rentability': 'Simule la Rentabilidad Real',
        'sim.simulate_desc': 'Pega un ASIN de Amazon arriba para analizar todas las tarifas FBA, Margen Neto y ROI en segundos.',
        'sim.iva_taxes': 'IVA / Impuestos',
        'sup.title': 'Proveedores',
        'sup.subtitle': 'Encuentra los mejores socios para tu negocio en Europa.',
        'sup.search_placeholder': 'Buscar por nombre, producto o nicho...',
        'sup.visit_site': 'Visitar Sitio',
        'sup.empty_title': 'No se encontraron proveedores',
        'sup.empty_desc': 'Intenta cambiar los filtros o buscar otros términos.',
        'sup.clear_filters': 'Limpiar filtros',
        'cat.all': 'Todas',
        'cat.general': 'General',
        'cat.home_kitchen': 'Casa y Cocina',
        'cat.toys_geek': 'Juguetes y Geek',
        'cat.electronics': 'Electrónica',
        'cat.beauty_health': 'Belleza y Salud',
        'cat.fashion_kids': 'Moda e Infantil',
        'cat.parties': 'Fiestas',
        'cat.tools_diy': 'Herramientas y Bricolaje',
        'cat.baby': 'Bebé',
        'cat.decor': 'Decoración',
        'cat.dynamic.retailer': 'Minorista (B2C)',
        'cat.dynamic.wholesale': 'Mayorista (B2B)',
        'cat.dynamic.b2b': 'B2B',
        'cat.dynamic.b2c': 'B2C',
        'cat.dynamic.retailer_b2b': 'Minorista y Mayorista',
        'analyze.button': 'Analizar Competencia',
        'analyze.modal_title': 'Análisis de Competencia IA',
        'analyze.weaknesses': 'Debilidades de la Competencia',
        'analyze.improvements': 'Oportunidades de Mejora',
        'analyze.processing': 'Extrayendo reseñas y analizando con IA...',
        'analyze.error': 'Error al analizar la competencia.',
        'analyze.credits_info': 'Consume 1 crédito premium',
        'analyze.recent_reviews': 'Últimas Reseñas',
        'summary.feb_2026': 'Feb 2026',
        'sim.pdf_recs_title': 'Recomendaciones Estratégicas',
        'lock.title': 'Límite de Créditos Alcanzado',

        // Profit Simulator
        'sim.title': 'Simulador de Lucro Real',
        'sim.product_cost': 'Costo del Producto',
        'sim.product_cost_help': 'El precio que paga a su proveedor por unidad, incluido el envío a su almacén.',
        'sim.tax_rate': 'Impuesto (%)',
        'sim.tax_rate_help': 'La tasa de impuestos de su negocio. Generalmente entre 4% y 15% en Brasil.',
        'sim.op_expenses': 'Gastos Operativos',
        'sim.op_expenses_help': 'Costo de embalaje, etiquetas y servicio de preparación por unidad.',
        'sim.ads_ppc': 'Inversión en Ads (PPC)',
        'sim.ads_ppc_help': 'Cuánto planea gastar en Amazon Advertising para obtener una venta. Un comienzo seguro es entre 10-15% del precio.',
        'sim.total_expenses': 'Gastos Totales',
        'sim.net_profit': 'Beneficio Neto',
        'sim.net_margin': 'Margen Neto',
        'sim.roi': 'ROI (Retorno)',
        'sim.export_pdf': 'Exportar Informe PDF',
        'sim.fba_vs_fbm': 'Comparativa FBA vs FBM',
        'sim.amazon_fulfilment': 'Logística de Amazon (FBA)',
        'sim.your_fulfilment': 'Tu Logística (FBM)',
        'sim.item_price': 'Precio del Artículo',
        'sim.delivery_charge': 'Gasto de Envío',
        'sim.amazon_fees': 'Tarifas de Amazon',
        'sim.referral_fee': 'Tarifa de Referencia',
        'sim.fulfilment_cost': 'Coste de Logística',
        'sim.storage_cost': 'Coste de Almacenamiento',
        'sim.jan_sep': 'Enero-Septiembre',
        'sim.oct_dec': 'Octubre-Diciembre',
        'sim.storage_per_unit': 'Costo mensual de almacenamiento por unidad',
        'sim.avg_inventory': 'Inventario Promedio',
        'sim.est_sales_month': 'Ventas Estimadas / Mes',
        'sim.storage_per_sold': 'Almacenamiento por unidad vendida',
        'sim.fixed_closing': 'Tasa fija de cierre',
        'sim.variable_closing': 'Tasa variable de cierre',
        'sim.digital_services': 'Tasas de servicios digitales',
        'sim.misc_cost': 'Costes Diversos',
        'sim.shipping_out': 'Costo de envío al cliente',
        'sim.total_sales_price': 'Precio total de venta',
        'sim.other_costs': 'Otros Costes',
        'sim.vat': 'IVA / Impuestos',
        'sim.cogs': 'COGS (Costo Prov.)',
        'sim.net_proceeds': 'Ingresos Netos',
        'sim.search_placeholder': 'Ingrese el ASIN del producto (ej: B086PHS2V8)',
        'sim.search_button': 'Buscar Producto',
        'sim.search_another': 'Buscar otro producto',
        'sim.break_even': 'Break-even',
        'sim.ads_impact': 'Impacto de Ads',
        'sim.ads_cost_unit': 'Inversión en Ads / un.',
        'sim.acos_sim': 'Simulación de ACOS (%)',
        'sim.ai_advice': 'Consejo de la IA',
        'sim.target_margin': 'Margen Objetivo (%)',
        'sim.profit_per_lot': 'Beneficio Estimado por Lote',
        'sim.strategy_fbm_title': 'Estrategia FBM',
        'sim.pdf_footer': 'Informe generado por Amazon Sem Segredos IA Suite | IVA: {taxRate}% | Los valores son estimaciones y pueden variar.',
        'sim.batch': 'Lote',
        'sim.units_abbr': 'Unid.',
        'sim.labor': 'Mano de Obra',
        'sim.material': 'Material',
        'sim.inbound': 'Envío a Amazon',
        'sim.strategy_advice': 'Impacto de Ads y Estrategia',
        'sim.iva': 'IVA / Impuestos',
        'sim.weight': 'Peso',
        'sim.sales_rank': 'BSR (Sales Rank)',
        'sourcing.title': 'Buscar Proveedores',
        'sourcing.desc': 'Buscamos automáticamente proveedores mayoristas para este producto.',
        'sourcing.alibaba': 'Buscar en Alibaba (Mayorista)',
        'sourcing.aliexpress': 'Buscar en AliExpress',
        'sourcing.1688': 'Buscar en 1688 (Fábricas)',
        'sourcing.google_lens': 'Búsqueda Visual (Google)',
        'sourcing.find_suppliers': 'Encontrar Proveedores',
        'sourcing.estimated_cost': 'Coste Sugerido por IA',
        'sourcing.rule_of_thumb': '* Estimación basada en la regla de oro de 30% del precio de venda para productos private label. Verifique siempre con proveedores reales.',
        'pf.filter': 'Filtrar',
        'pf.brand': 'Marca',
        'pf.min_price': 'Precio Mín',
        'pf.max_price': 'Precio Máx',
        'pf.clear_filters': 'Limpar Filtros',
        'pf.selected_analysis': 'Análisis de Ítems Seleccionados',
    },
    en: {
        // General
        'app.title': 'Amazon Sem Segredos IA Suite',
        'app.full_title': 'Amazon Sem Segredos IA Suite',
        'search.placeholder': 'Enter keyword or ASIN',
        'search.button': 'Search',
        'searching': 'Searching...',
        'suppliers.link': 'Find Suppliers on Alibaba',
        'rows.selected': 'Rows Selected',
        'filter.results': 'Filter Results',
        'search.image_tooltip': 'Upload Image',
        'search.camera_tooltip': 'Take Photo',
        'search.sources_title': 'Quick Source Search',
        'maintenance.title': 'System under Maintenance',
        'maintenance.desc': 'We are making improvements to the platform to offer an even better experience. We will be back soon!',
        'maintenance.restricted': 'Restricted Access',
        'maintenance.back': 'Back to Home',

        // Landing Page
        'nav.features': 'Features',
        'nav.pricing': 'Pricing',
        'nav.access': 'Access Platform',
        'hero.tag': 'New Intelligent Analysis Tool',
        'hero.title': 'Stop trying to sell. Start profiting on Amazon with real data.',
        'hero.subtitle': 'Analyze products, calculate FBA fees with surgical precision, and monitor competition in seconds. No guesswork, just net profit.',
        'hero.cta': 'Start free analysis now',
        'problem.title': 'Hidden fees stealing your profit?',
        'problem.bad.title': 'Complex spreadsheets that break',
        'problem.bad.desc': 'Hours lost manually updating FBA fees and hoping the formula is right.',
        'problem.good.tag': 'The Solution',
        'problem.good.title': 'Amazon Sem Segredos IA Suite',
        'problem.good.desc': 'Real-time reverse calculation. Paste an ASIN and see your ROI and net profit instantly.',
        'features.title': 'Everything you need to dominate the Buy Box',
        'features.subtitle': 'From product research to variation analysis, centralized in a single premium tool.',
        'features.finder.title': 'Product Finder',
        'features.finder.desc': 'Find the best products to sell on Amazon with detailed analysis of FBA fees, net profit margin, and ROI in seconds.',
        'features.mentor.title': 'Virtual Mentor',
        'features.mentor.desc': 'Ask your questions 24/7 to our AI trained by experts to assist you with strategies, blockers, and European suppliers.',
        'features.sourcing.title': 'Supplier Search',
        'features.sourcing.desc': 'Search for verified suppliers and reliable brands to stock your business and sell on Amazon Europe without headaches.',
        'features.optimizer.title': 'Listing Creator',
        'features.optimizer.desc': 'Create optimized titles, bullet points, and descriptions with AI, and generate professional images ready for Amazon standards.',
        'pricing.title': 'Plans that grow with you',
        'pricing.subtitle': 'Choose the ideal plan for your Amazon FBA journey stage.',
        'pricing.free.name': 'Free',
        'pricing.free.price': '$0',
        'pricing.free.f1': '30 initial credits',
        'pricing.free.f2': 'Basic analysis',
        'pricing.free.f3': 'Email support',
        'pricing.free.f4': '',
        'pricing.free.cta': 'Start Free',
        'pricing.starter.name': 'Starter',
        'pricing.starter.price': '€19',
        'pricing.starter.f1': '90 credits/month',
        'pricing.starter.f2': 'Basic analysis',
        'pricing.starter.f3': 'Advanced Listing Creator',
        'pricing.starter.f4': 'Email support',
        'pricing.starter.cta': 'Select Plan',
        'pricing.pro.name': 'Pro',
        'pricing.pro.price': '€49',
        'pricing.pro.f1': '200 credits/month',
        'pricing.pro.f2': 'Deep AI analysis',
        'pricing.pro.f3': 'Pro Listing Creator',
        'pricing.pro.f4': 'Email and WhatsApp support',
        'pricing.pro.recommended': 'Recommended',
        'pricing.pro.cta': 'Select Plan',
        'pricing.premium.name': 'Premium',
        'pricing.premium.price': '€99',
        'pricing.premium.f1': '600 credits/month',
        'pricing.premium.f2': 'Deep AI analysis',
        'pricing.premium.f3': 'Pro Listing Creator',
        'pricing.premium.f4': 'Email and WhatsApp support',
        'pricing.premium.f5': 'Exclusive Mentorship (VIP)',
        'pricing.premium.cta': 'Select Plan',
        'footer.rights': 'All rights reserved.',

        // Support
        'support.widget_title': 'Support Center',
        'support.modal_title': 'Support Center',
        'support.modal_subtitle': 'How can we help you today?',
        'support.vip_title': 'VIP WhatsApp Support',
        'support.vip_desc': 'Priority service for you.',
        'support.whatsapp_button': 'Call on WhatsApp',
        'support.whatsapp_text': 'Hello! I would like help with the Amazon Sem Segredos IA Suite platform.',
        'support.or_ticket': 'Or send a ticket below',
        'support.subject_label': 'Subject',
        'support.subject_placeholder': 'Issue summary',
        'support.message_label': 'Message',
        'support.message_placeholder': 'Describe your problem or question in detail...',
        'support.cancel': 'Cancel',
        'support.send': 'Send Ticket',
        'support.sending': 'Sending...',
        'support.success_title': 'Ticket Sent!',
        'support.success_desc': 'Our team has received your message and will respond shortly.',
        'support.error_default': 'There was a communication error. Please try again.',
        'support.error_send': 'Error sending ticket.',
        'profile.user_placeholder': 'User',
        'profile.upgrade': 'Upgrade Plan',
        'profile.credits': 'Credits',
        'ads.premium_desc': 'This module uses Reinforcement Learning to optimize your bids and keywords automatically. Available in the Premium plan.',
        'checkout.error_base': 'Error starting checkout. Please try again.',
        'checkout.error_conn': 'Connection error. Check your internet.',
        'common.cancel': 'Cancel',
        'sidebar.tools': 'Tools',
        'common.unit': 'unit',
        'common.product': 'Product',

        // Product Finder Headers
        'col.product_details': 'Product Details',
        'col.asin': 'ASIN',
        'col.brand': 'Brand',
        'col.price': 'Price',
        'col.sales': 'Sales',
        'col.sales_graph': 'Sales Graph',
        'col.ranking_bsr': 'Ranking (BSR)',
        'col.revenue': 'Revenue',
        'col.bsr': 'BSR',
        'col.fba_fees': 'FBA Fees',
        'col.active_sellers': 'Active Sellers',

        // Summary Cards
        'summary.search_volume': 'Search Volume',
        'summary.total_revenue': 'Total Revenue',
        'summary.avg_revenue': 'Avg Revenue',
        'summary.avg_price': 'Avg Price',
        'summary.avg_bsr': 'Avg BSR',
        'summary.avg_reviews': 'Avg Reviews',
        'summary.success_score': 'Success Score',

        // Empty States / Errors
        'error.no_products': 'No products found. Start a search.',
        'error.insufficient_credits': 'Insufficient credits. Please top up your balance.',
        'error.internal_server': 'Internal error. Please try again later.',
        'error.search_failed': 'Error searching for product. Please check your connection or try again.',
        'error.checkout_failed': 'Error starting checkout. Please try again.',
        'error.connection': 'Connection error. Check your internet.',

        // Product Categories
        'category.Beauty': 'Beauty',
        'category.Electronics': 'Electronics',
        'category.Home': 'Home',
        'category.Kitchen': 'Kitchen',
        'category.Toys': 'Toys',
        'category.Sports': 'Sports',
        'category.Unknown': 'General',

        // Modules
        'module.dashboard': 'Overview',
        'module.mentor': 'Virtual Mentor',
        'module.product_finder': 'Product Finder',
        'module.supplier_finder': 'Supplier Finder',
        'module.profit_calculator': 'Real Profit Calculator',
        'module.listing_optimizer': 'Listing Optimizer',
        'module.ads_manager': 'Ads Manager',
        'module.settings': 'Settings',
        'module.account': 'My Account',
        'module.logout': 'Logout',
        'auth.forgot_password': 'Forgot password',
        'auth.reset_password': 'Reset Password',
        'auth.back_to_login': 'Back to Login',
        'auth.send_reset_link': 'Send Recovery Link',
        'auth.reset_email_sent': 'Recovery link sent! Check your email.',

        // Profile & Billing
        'profile.title': 'Profile',
        'profile.change_password': 'Change Password',
        'profile.buy_credits': 'Buy Credits',
        'profile.change_plan': 'Change Plan',
        'profile.current_plan': 'Current Plan',
        'profile.admin_label': 'Administrator',
        'profile.pro_label': 'Pro Plan',
        'profile.welcome': 'Welcome',
        'profile.credits_label': 'Credits',

        // Plans
        'plans.starter': 'Starter',
        'plans.starter_desc': 'Ideal for starting',
        'plans.starter_features': '5 Initial Credits',
        'plans.pro': 'Pro Plan',
        'plans.pro_desc': 'For growing sellers',
        'plans.pro_price': '29€/month',
        'plans.premium': 'Premium Plan',
        'plans.premium_desc': 'Full AI Power',
        'plans.premium_price': '49€/month',
        'plans.select': 'Select Plan',
        'plans.free': 'Free',
        'plans.upgrade': 'Upgrade Now',

        'modal.details': 'Details',
        'modal.est_sales': 'Est. Sales',
        'modal.est_revenue': 'Est. Revenue',
        'modal.price': 'Price',
        'modal.sellers': 'Sellers',
        'modal.reviews': 'Reviews',
        'modal.score': 'Score',
        'modal.fba_fees': 'FBA Fees',
        'modal.view_amazon': 'View on Amazon',
        'modal.units_month': 'Units / Month',
        'modal.footer_disclaimer': 'Data provided by Amazon SP-API • Estimates based on category',
        'modal.unknown_brand': 'Unknown Brand',
        'mentor.title': 'Our 9 Specialized Agents',
        'mentor.subtitle': 'Each agent is trained to solve specific business challenges.',

        // Listing Optimizer
        'lo.intro': 'Hello! I am your Amazon expert. Let\'s create a winning listing for Amazon? First, what is the name of your product?',
        'lo.q.productName': 'What is the name of your product?',
        'lo.q.category': 'What is its category? (Ex: Kitchen, Sports, Electronics)',
        'lo.q.material': 'What material is it made of? (Ex: Stainless Steel, Organic Cotton)',
        'lo.q.benefits': 'What are the main benefits? (List 2 or 3)',
        'lo.q.differentiators': 'What differentiates it from competitors? (Your differentiator)',
        'lo.q.audience': 'Who is your target audience? (Ex: Moms, Athletes, Gamers)',
        'lo.q.problem': 'What problem does it solve for the customer?',
        'lo.q.usage': 'What is the main usage? (Ex: Daily, Gift, Travel)',
        'lo.processing.text': 'Perfect! I am creating your optimized listing now. This may take a few seconds...',
        'lo.success.text': 'Text listing generated successfully! Now, to finish, I need you to send a photo of the product (white background is ideal) so I can generate visual variations.',
        'lo.error.text': 'Oops, I had a problem generating the text. Please try again.',
        'lo.processing.image': 'Received the image! Generating optimized variations for the listing...',
        'lo.success.image': 'Ready! Your listing is complete. See below.',
        'lo.error.image': 'Error generating images. Please upload a valid image',
        'lo.ui.assistant': 'Assistant',
        'lo.ui.history': 'History',
        'lo.ui.history.empty': 'No saved listings.',
        'lo.ui.upload': 'Click to upload photo',
        'lo.ui.input_placeholder': 'Type your answer...',
        'lo.ui.title': 'Your listing will appear here',
        'lo.ui.subtitle': 'Answer the questions so our AI can create a high-conversion listing for your product.',
        'lo.ui.save': 'Save Listing',
        'lo.ui.generating_images': 'Generating Images...',
        'lo.ui.title_label': 'Ad Title',
        'lo.ui.bullets_label': 'Key Features',
        'lo.ui.desc_label': 'Product Description',
        'lo.ui.keywords_label': 'Search Keywords',
        'lo.ui.benefits_summary': 'Benefits Summary',
        'mentor.placeholder': 'Ask your mentor anything...',
        'mentor.unclear': "I couldn't understand, could you repeat?",
        'mentor.specialized': 'Specialized Agent',
        'mentor.you': 'You',
        'mentor.video_rec': 'Video Recommended by Mentor',
        'mentor.access_tool': 'Access Tool',
        'mentor.analyzing': 'Analyzing...',
        'pf.title_unavailable': 'Title Unavailable',
        'pf.est_sales_month': 'estimated units / month',
        'pf.avg_net_margin': 'Avg Net Margin',
        'pf.price_fba_fees': 'Price - FBA Fees',
        'pf.comp_level': 'Competition Level',
        'pf.active_sellers_per_listing': 'active sellers per listing',
        'pf.empty_title': 'Where is the profit today?',
        'pf.empty_desc': 'Paste an ASIN or search by keyword to start discovering highly profitable products.',
        'pf.first_search': 'Make First Search',
        'pf.loading_more': 'Loading...',
        'pf.load_more': 'Load More Results',
        'pf.no_more': 'No More Results',
        'sim.asin_error': 'Please enter a valid ASIN (e.g., B086PHS2V8). The calculator only accepts ASINs.',
        'sim.search_failed': 'Error searching for product on Amazon.',
        'sim.report_title': 'AI Strategic Report',
        'sim.generated_at': 'Generated at',
        'sim.suite_name': 'Amazon Sem Segredos AI Suite',
        'sim.analyzed_product': 'Analyzed Product',
        'sim.no_product_search': 'No product searched. Analysis based on manually entered values.',
        'sim.fba_title': 'Fulfillment by Amazon (FBA)',
        'sim.fbm_title': 'Fulfillment by Merchant (FBM)',
        'sim.break_even_desc': 'Minimum price to avoid loss considering all current costs.',
        'sim.fbm_break_even_desc': 'Considering your own logistics and shipping costs.',
        'sim.fba_ads_impact_desc': 'Average advertising cost spent to sell one unit. Directly impacts your net margin.',
        'sim.edit_costs': 'Edit cost breakdown',
        'sim.fbm_storage_hint': 'Enter your storage costs',
        'sim.simulate_rentability': 'Simulate Real Profitability',
        'sim.simulate_desc': 'Paste an Amazon ASIN above to analyze all FBA fees, Net Margin and ROI in seconds.',
        'sim.iva_taxes': 'VAT / Taxes',
        'sup.title': 'Suppliers',
        'sup.subtitle': 'Find the best partners for your business in Europe.',
        'sup.search_placeholder': 'Search by name, product or niche...',
        'sup.visit_site': 'Visit Site',
        'sup.empty_title': 'No suppliers found',
        'sup.empty_desc': 'Try changing filters or searching for other terms.',
        'sup.clear_filters': 'Clear filters',
        'cat.all': 'All',
        'cat.general': 'General',
        'cat.home_kitchen': 'Home & Kitchen',
        'cat.toys_geek': 'Toys & Geek',
        'cat.electronics': 'Electronics',
        'cat.beauty_health': 'Beauty & Health',
        'cat.fashion_kids': 'Fashion & Kids',
        'cat.parties': 'Parties',
        'cat.tools_diy': 'Tools & DIY',
        'cat.baby': 'Baby',
        'cat.decor': 'Decoration',
        'cat.dynamic.retailer': 'Retailer (B2C)',
        'cat.dynamic.wholesale': 'Wholesale (B2B)',
        'cat.dynamic.b2b': 'B2B',
        'cat.dynamic.b2c': 'B2C',
        'cat.dynamic.retailer_b2b': 'Retailer & Wholesale',
        'analyze.button': 'Analyze Competition',
        'analyze.modal_title': 'AI Competition Analysis',
        'analyze.weaknesses': 'Competitor Weaknesses',
        'analyze.improvements': 'Improvement Opportunities',
        'analyze.processing': 'Scraping reviews and analyzing with AI...',
        'analyze.error': 'Error analyzing competition.',
        'analyze.credits_info': 'Consumes 1 premium credit',
        'analyze.recent_reviews': 'Latest Reviews',
        'summary.feb_2026': 'Feb 2026',
        'sim.pdf_recs_title': 'Strategic Recommendations',
        'lock.title': 'Credit Limit Reached',

        // Profit Simulator
        'sim.title': 'Real Profit Simulator',
        'sim.product_cost': 'Product Cost',
        'sim.product_cost_help': 'The price you pay your supplier per unit, including shipping to your warehouse.',
        'sim.tax_rate': 'Tax (%)',
        'sim.tax_rate_help': 'Your business tax rate (e.g., SIMPLES Nacional). Usually between 4% and 15% in Brazil.',
        'sim.op_expenses': 'Operational Expenses',
        'sim.op_expenses_help': 'Cost of packaging, labels, and prep service per unit.',
        'sim.ads_ppc': 'Ads Investment (PPC)',
        'sim.ads_ppc_help': 'How much you plan to spend on Amazon Advertising to get one sale. A safe start is 10-15% of the price.',
        'sim.total_expenses': 'Total Expenses',
        'sim.net_profit': 'Net Profit',
        'sim.net_margin': 'Net Margin',
        'sim.roi': 'ROI (Return)',
        'sim.export_pdf': 'Export PDF Report',
        'sim.fba_vs_fbm': 'Comparison FBA vs FBM',
        'sim.amazon_fulfilment': 'Amazon Fulfilment (FBA)',
        'sim.your_fulfilment': 'Your Fulfilment (FBM)',
        'sim.item_price': 'Item Price',
        'sim.delivery_charge': 'Delivery Charge',
        'sim.amazon_fees': 'Amazon Fees',
        'sim.referral_fee': 'Referral Fee',
        'sim.fulfilment_cost': 'Fulfilment Cost',
        'sim.storage_cost': 'Storage Cost',
        'sim.jan_sep': 'January-September',
        'sim.oct_dec': 'October-December',
        'sim.storage_per_unit': 'Monthly storage cost per unit',
        'sim.avg_inventory': 'Average Inventory',
        'sim.est_sales_month': 'Est. Sales / Month',
        'sim.storage_per_sold': 'Storage per unit sold',
        'sim.fixed_closing': 'Fixed closing fee',
        'sim.variable_closing': 'Variable closing fee',
        'sim.digital_services': 'Digital services fees',
        'sim.misc_cost': 'Miscellaneous Cost',
        'sim.shipping_out': 'Delivery Charge',
        'sim.total_sales_price': 'Total Sales Price',
        'sim.other_costs': 'Other Costs',
        'sim.vat': 'VAT / Taxes',
        'sim.cogs': 'Cost of Goods Sold (COGS)',
        'sim.net_proceeds': 'Net Proceeds',
        'sim.search_placeholder': 'Search ASIN or Keyword...',
        'sim.search_button': 'Search Product',
        'sim.search_another': 'Search another product',
        'sim.break_even': 'Break-even Price (Balance Point)',
        'sim.ads_impact': 'Ads Impact (PPC)',
        'sim.ads_cost_unit': 'Ads Cost per Unit',
        'sim.acos_sim': 'ACOS Simulation (%)',
        'sim.ai_advice': 'AI Strategic Advice',
        'sim.target_margin': 'Target Margin (%)',
        'sim.profit_per_lot': 'Estimated Profit per Batch',
        'sourcing.title': 'Find Suppliers',
        'sourcing.desc': 'We automatically search for wholesale suppliers for this product.',
        'sourcing.alibaba': 'Search Alibaba (Wholesale)',
        'sourcing.aliexpress': 'Search AliExpress',
        'sourcing.1688': 'Search 1688 (Factories)',
        'sourcing.google_lens': 'Visual Search (Google)',
        'sourcing.find_suppliers': 'Find Suppliers',
        'sourcing.estimated_cost': 'AI Suggested Cost',
        'sourcing.rule_of_thumb': '* Estimate based on the golden rule of 30% of sale price for private label products. Always verify with real suppliers.',
        'pf.emerging': 'Emerging',
        'pf.units_month': 'units/month',
        'pf.bsr_tool_tip': 'BSR currently unavailable. Market interest estimated via monthly search volume.',
        'pf.bsr_unavailable_tip': 'BSR unavailable. Estimated sales based on market interest.',
        'pf.sales_census_tip': 'Estimated sales in the last 30 days based on the 2025 BSR Census for {category}.',
        'pf.top_percentile_tip': 'This product is among the top {total} items in the {category} category (Based on 2025 Census).',
        'pf.price_fallback_tip': 'Price based on lowest available offer (Professional Seller)',
        'pf.msrp_tip': 'List Price (MSRP). Actual selling price may be lower.',
        'pf.fba_breakdown_tip': 'Referral ({rate}%): {referral} | Fulfillment: {fulfillment}{estimate}',
        'pf.opportunity_score': 'Opportunity Score',
        'pf.opportunity_score_desc': '% of Top 1% or 3% products',
        'pf.filter': 'Filter',
        'pf.brand': 'Brand',
        'pf.min_price': 'Min Price',
        'pf.max_price': 'Max Price',
        'pf.clear_filters': 'Clear Filters',
        'pf.selected_analysis': 'Selected Items Analysis',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const { user, loading } = useAuth();

    // Initialize from localStorage or default to 'pt'
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('app_language');
        return (saved as Language) || 'pt';
    });

    // Detect browser language only for landing page (unauthenticated users)
    useEffect(() => {
        // Skip if preference is already saved or if user is logged in
        const saved = localStorage.getItem('app_language');
        if (saved || loading || user) return;

        const browserLang = navigator.language.toLowerCase();
        let detected: Language = 'en';

        if (browserLang.startsWith('pt')) {
            detected = 'pt';
        } else if (browserLang.startsWith('es')) {
            detected = 'es';
        }

        if (detected !== language) {
            setLanguageState(detected);
        }
    }, [user, loading, language]);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('app_language', lang);
    };

    const t = (key: string): string => {
        // @ts-ignore
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
